docs: update challenge 1 in dev onboarding
OpenBeta/docs.openbeta.io pull request #37
Opened 2023-07-02 08:32 UTC by actuallyyun

related to [issue #896 in open-tacos repo ](https://github.com/OpenBeta/open-tacos/pull/896)

Updated instructions to sync with the changes in contributors map json file. 

![Screenshot 2023-07-02 at 11 32 34](https://github.com/OpenBeta/docs.openbeta.io/assets/87448230/fb84ff5d-644e-4e32-a6ce-6a801117fd4a)

2023-07-03 18:35 UTC, musoke requested changes

2023-07-03 18:35 UTC, musoke commented on docs/how-to-contribute/dev-onboarding.md
> +- `"coordinates"`
make it clear if these are coordinates of the person or crag

2023-08-04 19:15 UTC, musoke approved these changes

2023-08-05 03:19 UTC, vnugent approved these changes

2023-08-05 03:19 UTC, merged