Typos and small changes
OpenBeta/docs.openbeta.io pull request #46
Opened 2024-10-29 23:22 UTC by AStonedApe

Fixed a few typos and changed "data" to "content" to make it sound less intimidating to non-technical folks.

2024-10-29 23:22 UTC, AStonedApe commented
I hope I did this right, still learning how to use github

2024-10-30 11:57 UTC, musoke requested changes
Thank you! This looks good overall.  Could you fix the one error I highlighted?

2024-10-30 11:57 UTC, musoke commented on docs/introduction/about.mdx
Looks like one new here

2024-10-31 07:43 UTC, closed without merging

2024-10-31 13:04 UTC, musoke commented
Did you mean to close this?  You should be able to add one more commit to the same pull request.